# Generated by Django 5.2.5 on 2025-08-20 16:34

import django.db.models.deletion
import helpers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='course.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.term')),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseclass')),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
    ]
