# Generated by Django 5.2.5 on 2025-09-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('employee', '0003_alter_careerstep_options'),
        ('helpers', '0002_alter_term_options_alter_term_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='courseinstructor',
            options={'ordering': ['-assigned_on', '-created_on']},
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='assigned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='instructors',
            field=models.ManyToManyField(related_name='course_classes', through='course.CourseInstructor', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.courseclass'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employee.employee'),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'code'), name='unique_course_code_per_course'),
        ),
    ]
