# Generated by Django 5.2.5 on 2025-09-18 07:45

import django.db.models.deletion
import helpers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_alter_courseinstructor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.term'),
        ),
    ]
