# Generated by Django 5.2.5 on 2025-09-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_term_alter_courseclass_term'),
        ('employee', '0003_alter_careerstep_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseclass',
            options={'ordering': ['-created_on'], 'verbose_name': 'Course Class', 'verbose_name_plural': 'Course Classes'},
        ),
        migrations.AlterModelOptions(
            name='courseinstructor',
            options={'ordering': ['-assigned_on', '-created_on'], 'verbose_name': 'Course Instructor', 'verbose_name_plural': 'Course Instructors'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-start_date'], 'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
        migrations.RemoveConstraint(
            model_name='courseclass',
            name='unique_course_code_per_course',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text="The unique identifier for the course (e.g., 'MATH101').", max_length=50, unique=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the course content.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='The full name of the course.', max_length=200, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='code',
            field=models.CharField(help_text="A unique code for the class (e.g., 'MATH101-FALL2025-01').", max_length=50, verbose_name='Class Code'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(help_text='The abstract course this class is an instance of.', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='instructors',
            field=models.ManyToManyField(help_text='The instructors assigned to this class.', related_name='course_classes', through='course.CourseInstructor', to='employee.employee', verbose_name='Instructors'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='term',
            field=models.ForeignKey(help_text='The academic term this class is offered in.', on_delete=django.db.models.deletion.PROTECT, to='course.term', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='assigned_on',
            field=models.DateField(blank=True, help_text='The date the instructor was officially assigned.', null=True, verbose_name='Assigned On'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='course_class',
            field=models.ForeignKey(help_text='The course class assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.courseclass', verbose_name='Course Class'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='exit_date',
            field=models.DateField(blank=True, help_text="The date the instructor's assignment ended.", null=True, verbose_name='Exit Date'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(help_text='The employee assigned as an instructor.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employee.employee', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(help_text='The official end date of the term.', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(help_text="A unique name for the academic term (e.g., 'Fall 2025').", max_length=100, unique=True, verbose_name='Term Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(help_text='The official start date of the term.', verbose_name='Start Date'),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'term', 'code'), name='unique_class_code_per_term_and_course'),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('exit_date__isnull', True)), fields=('course_class', 'instructor'), name='unique_active_assignment_per_instructor_per_class'),
        ),
    ]
