# Generated by Django 5.2.5 on 2025-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
