# Generated by Django 5.2.5 on 2025-09-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_term_alter_courseclass_term'),
        ('helpers', '0002_alter_term_options_alter_term_name'),
        ('student', '0005_alter_studentstatus_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
    ]
