# Generated by Django 5.2.5 on 2025-08-20 16:32

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import helpers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('on_trial', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
