# Generated by Django 5.2.5 on 2025-08-20 16:34

import helpers.fields
import institute.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('institution_name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=institute.models.institute_logo_upload_path)),
                ('post_office_box', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('parish', models.CharField(blank=True, max_length=100)),
                ('cell_village', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('inst_nssf_nr', models.CharField(blank=True, max_length=100)),
                ('inst_paye_number', models.CharField(blank=True, max_length=100)),
                ('tax_flag', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('business_year_start_date', models.DateField(default='1900-01-01')),
                ('business_year_end_date', models.DateField(blank=True, null=True)),
                ('last_year_closure_date', models.DateField(default='1900-01-01')),
            ],
            options={
                'verbose_name': 'Institute Profile',
                'verbose_name_plural': 'Institute Profiles',
            },
        ),
    ]
