# backend/helpers/upload_path.py
import os
import uuid
from django.db import connection
from django.utils.deconstruct import deconstructible
from django.utils.text import slugify


@deconstructible
class TenantFilePath:
    """
    A callable class that generates a dynamic, tenant-aware upload path.
    It uses the model's `idx` for identification and preserves the original filename.
    The storage backend (like S3Boto3Storage) will handle filename collisions
    by appending a unique suffix if a file with the same name already exists.
    """

    def __init__(self, sub_path):
        self.sub_path = sub_path

    def __call__(self, instance, filename):
        # Get schema name for tenant isolation
        schema_name = connection.schema_name

        # Get instance's app and model name for organization
        app_label = instance._meta.app_label
        model_name = instance._meta.model_name.lower()

        # Get a unique identifier for the instance using your `idx` field.
        if hasattr(instance, "idx") and instance.idx:
            instance_identifier = str(instance.idx)
        else:
            # Fallback if idx is not set yet (e.g., on initial save before commit)
            # A truly unique path is still generated by this folder.
            instance_identifier = str(uuid.uuid4())

        # Sanitize the original filename to make it URL-safe
        # For example, "my profile picture.jpg" becomes "my-profile-picture.jpg"
        filename_base, filename_ext = os.path.splitext(filename)
        safe_filename = f"{slugify(filename_base)}{filename_ext}"

        # Construct the final path. The filename is kept as is.
        # The storage backend's `get_available_name` method will resolve any conflicts.
        return os.path.join(
            "tenants",
            schema_name,
            app_label,
            model_name,
            instance_identifier,
            self.sub_path,
            safe_filename,
        )


employee_photo_upload_path = TenantFilePath(sub_path="employee-photos")
student_photo_upload_path = TenantFilePath(sub_path="student-photos")
institute_logo_upload_path = TenantFilePath(sub_path="institute-logos")
