# Generated by Django 5.2.5 on 2025-08-20 16:34

import employee.models
import helpers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('function', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competence_area', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('family_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employee.models.employee_photo_upload_path)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
    ]
