# Generated by Django 5.2.5 on 2025-09-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerstep',
            options={'ordering': ['-start_date']},
        ),
    ]
