# Generated by Django 5.2.5 on 2025-09-25 18:29

import helpers.storage
import helpers.upload_path
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_careerstep_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=helpers.storage.CustomImageField(blank=True, null=True, upload_to=helpers.upload_path.TenantFilePath(sub_path='employee-photos')),
        ),
    ]
