# Generated by Django 5.2.5 on 2025-09-06 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.courseclass'),
        ),
    ]
