# Generated by Django 5.2.5 on 2025-09-18 07:39

import django.utils.timezone
import helpers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_alter_courseinstructor_options_and_more'),
        ('helpers', '0002_alter_term_options_alter_term_name'),
        ('student', '0003_studentstatus_course_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='date',
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='idx',
            field=helpers.fields.IDXField(blank=True, editable=False, length=8, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='studentstatus',
            index=models.Index(fields=['student', 'status'], name='student_stu_student_3180e0_idx'),
        ),
    ]
