# Generated by Django 5.2.5 on 2025-09-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_term_alter_courseclass_term'),
        ('student', '0004_remove_student_user_remove_studentstatus_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.term'),
        ),
    ]
