# Generated by Django 5.2.5 on 2025-09-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_options_alter_courseclass_options_and_more'),
        ('student', '0005_alter_studentstatus_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custodian',
            options={'ordering': ['student__family_name', 'name'], 'verbose_name': 'Custodian', 'verbose_name_plural': 'Custodians'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['family_name', 'first_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentstatus',
            options={'ordering': ['-created_on'], 'verbose_name': 'Student Status', 'verbose_name_plural': 'Student Statuses'},
        ),
        migrations.AlterField(
            model_name='custodian',
            name='email',
            field=models.EmailField(blank=True, help_text="The custodian's email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='name',
            field=models.CharField(help_text="The custodian's full name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='phone',
            field=models.CharField(blank=True, help_text="The custodian's phone number.", max_length=64),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='relation',
            field=models.CharField(help_text="The custodian's relationship to the student (e.g., Father, Mother).", max_length=64),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='student',
            field=models.ForeignKey(help_text='The student this custodian is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='custodians', to='student.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(help_text="The student's date of birth.", verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='family_name',
            field=models.CharField(help_text="The student's last name or family name.", max_length=150, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text="The student's first name.", max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text="The student's phone number.", max_length=64, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='An optional profile photo for the student.', null=True, upload_to='students/photos/'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='comment',
            field=models.TextField(blank=True, help_text="Additional comments or notes about the student's status."),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course the student is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='course.course'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='course_class',
            field=models.ForeignKey(blank=True, help_text='The specific class the student is enrolled in, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.courseclass'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='status',
            field=models.CharField(choices=[('enquired', 'Enquired'), ('active', 'Active'), ('closed', 'Closed')], default='enquired', help_text='The current status of the student (e.g., Enquired, Active, Closed).', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='student',
            field=models.ForeignKey(help_text='The student this status entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='student.student'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='term',
            field=models.ForeignKey(blank=True, help_text='The academic term for this status entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.term'),
        ),
        migrations.AlterUniqueTogether(
            name='custodian',
            unique_together={('student', 'name', 'relation')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('family_name', 'first_name', 'dob')},
        ),
        migrations.AddConstraint(
            model_name='studentstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'course_class', 'status'), name='unique_active_enrollment_per_class'),
        ),
    ]
