# Generated by Django 5.2.5 on 2025-09-25 18:29

import helpers.storage
import helpers.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_options_alter_courseclass_options_and_more'),
        ('student', '0006_alter_custodian_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=helpers.storage.CustomImageField(blank=True, help_text='An optional profile photo for the student.', null=True, upload_to=helpers.upload_path.TenantFilePath(sub_path='student-photos')),
        ),
        migrations.AddConstraint(
            model_name='studentstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'enquired')), fields=('student', 'course_class'), name='unique_enquired_enrollment_per_class'),
        ),
    ]
