# Generated by Django 5.2.5 on 2025-09-26 13:01

from django.db import migrations


def populate_emails(apps, schema_editor):
    """
    Find all students without an email and give them a unique one
    based on their ID.
    """
    Student = apps.get_model("student", "Student")
    for student in Student.objects.filter(email__isnull=True):
        student.email = f"student_{student.id}@example.com"
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_student_email"),
    ]

    operations = [
        migrations.RunPython(populate_emails, reverse_code=migrations.RunPython.noop),
    ]
